-- Create database Attrition;

use Attrition;

select * from HR;

-------------------------

--1). OverAll Attrition.
SELECT COUNT(CASE WHEN Attrition = 1 THEN 1 END) AS ATTRITION_COUNT, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR;

--2). Presence of Overtime and Attrition Correlation (NO COORELATION HERE).
SELECT OVERTIME, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR
WHERE ATTRITION = 1
GROUP BY OVERTIME;
------------------ AS PEOPLE WHO HAVE DONE OVERTIME AND WHO DON'T THERE RATIO IS SAME

--3). Overall gender distribution in the dataset.
SELECT GENDER, COUNT (*) AS TOTAL_EMPLOYEES FROM HR
GROUP BY GENDER;

--4). From people who done attrition, how many are male and how many are female? (To analyze the toxic environment of office)
SELECT GENDER, COUNT (*) AS TOTAL_EMPLOYEES FROM HR
WHERE ATTRITION = 1
GROUP BY GENDER;

--5). Relation b/w Performance Rating and Attrition
SELECT PERFORMANCERATING, COUNT(CASE WHEN Attrition = 1 THEN 1 END) AS ATTRITION_COUNT FROM HR
GROUP BY PERFORMANCERATING;
---------------------------CONCLUSION:- Who got performance rating as 3 has higher Attrition rate.(Negative correlation)

--6). Relation b/w Percent Salaery Hike and Attrition count
SELECT PERCENTSALARYHIKE, COUNT (*) AS ATTRITION_COUNT FROM HR
WHERE ATTRITION = 1
GROUP BY PERCENTSALARYHIKE
ORDER BY ATTRITION_COUNT DESC;
---------------------------CONCLUSION:- Who got less PercentSalaryHike has higher Attrition rate.(Negative correlation)

--7). Relation b/w Years In Current Role and Attrition count.
--(Calculating the avg of the years in current role and attrition count for people who exceeds the avg of the years in current role)
SELECT YearsInCurrentRole, COUNT(CASE WHEN ATTRITION = 1 THEN 1 END) AS ATTRITION_COUNT
FROM HR
WHERE YearsInCurrentRole > (SELECT AVG(CAST(YEARSINCURRENTROLE AS INT)) FROM HR)
GROUP BY YearsInCurrentRole
ORDER BY YearsInCurrentRole;
--------------------------- EMPLOYEES WHO ARE WORKING IN THE COMPANY FROM LAST 5-10 YEARS ARE HAVING THE HIGHEST ATTRITION COUNT

select * from HR;

--8).EMPLOYEE ATTRITION BASED ON THE AGE RANGE
SELECT CASE WHEN AGE <= 29 THEN '18-29'
            WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
			WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
			WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
			ELSE '60 OR OLDER'
			END AS 'AGE RANGE', COUNT(*) AS 'NUMBER OF ATTRITION COUNT BASED ON AGE RANGE'
FROM HR
WHERE ATTRITION = 1 AND YearsAtCompany >= 2
GROUP BY CASE WHEN AGE <= 29 THEN '18-29'
            WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
			WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
			WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
			ELSE '60 OR OLDER'
			END
ORDER BY [AGE RANGE];
----------------------------AGE GROUP OF '18-29' AND '30-39' HAVE THE MAXIMUM ATTRITION COUNTS FOR THOSE EMPLOYEES 
--WHO HAVE BEEN WORKING IN THE COMPANY FROM LAST 1 


--9).DEPARTMENT WISE ATTRITION COUNT
SELECT DEPARTMENT, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE Attrition = 1
GROUP BY Department
ORDER BY ATTRITION_COUNT DESC;
------------------------------ R&D AND SALES DEPARTMENT ARE HAVING THE MAX ATTRITION WITH ALMOST 95%


--10).EFFECT OF ENVIRONMENT SATISFACTION, JOB SATISFACTION AND RELATIONSHIP SATISFACTION ON ATTRITION COUNTS
SELECT ENVIRONMENTSATISFACTION, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE ATTRITION = 1
GROUP BY ENVIRONMENTSATISFACTION
ORDER BY ATTRITION_COUNTS DESC;
--------------------------- THERE IS NO CORRELATION BETWEEN THE ENVIRONMENT SATISFACTION AND ATTRITION COUNTS

SELECT JOBSATISFACTION, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE ATTRITION = 1
GROUP BY JOBSATISFACTIONs
ORDER BY ATTRITION_COUNTS DESC;
----------------------------------- THERE IS NO CORRELATION BETWEEN THE JOB SATISFACTION AND ATTRITION COUNTS


SELECT RELATIONSHIPSATISFACTION, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE ATTRITION = 1
GROUP BY RELATIONSHIPSATISFACTION
ORDER BY ATTRITION_COUNTS DESC;
-------------------------- THERE IS NO CORRELATION BETWEEN THE RELATIONSIP SATISFACTION AND ATTRITION COUNTS



--11).WORK LIFE BALANCE AND ATTRITION COUNTS
SELECT WORKLIFEBALANCE, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE Attrition = 1
GROUP BY WorkLifeBalance
ORDER BY ATTRITION_COUNTS DESC;
--------------------------------- THERE IS NO RELATION BETWEEN THE WORK LIFE BALANCE AND ATTRITION COUNTS

--12).DISTANCE FROM HOME AND ATTRITION COUNTS
select distancefromhome, count(*) as attr_count
from HR
where attrition = 1
group by distancefromhome
order by DistanceFromHome desc, attr_count desc;
----------------------------------- THERE IS NO RELATION BETWEEN DISTANCE FROM HOME AND ATTRITION COUNTS

